name: plugin_creation
description: "A new Flutter plugin."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.example.plugin_creation
        pluginClass: PluginCreationPlugin
      ios:
        pluginClass: PluginCreationPlugin
      linux:
        pluginClass: PluginCreationPlugin
      macos:
        pluginClass: PluginCreationPlugin
      windows:
        pluginClass: PluginCreationPluginCApi
      web:
        pluginClass: PluginCreationWeb
        fileName: plugin_creation_web.dart

